version: "2"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15673:15673
      - 5673:5673
    network_mode: host

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-service:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-service:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888
 
  documentcrawler:
    image: document-crawler-service:latest
    build: document-crawler-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - rabbitmq
    ports:
      - 8193:8193
    expose:
      - 8193

  searchservice:
    image: search-service:latest
    build: search-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - rabbitmq
    ports:
      - 8090:8090
    expose:
      - 8090
 

  nlpservice:
    image: nlp-service:latest
    build: nlp-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8098:8098
    expose:
      - 8098

  evaluatorservice:
    image: evaluator-service:latest
    build: evaluator-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8082:8082
    expose:
      - 8082

  userloginservice:
    image: user-login-service:latest
    build: user-login-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8132:8132
    expose:
      - 8132

  userregisterservice:
    image: user-register-service:latest
    build: user-register-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8089:8089
    expose:
      - 8089
  
  knowledgeindexerservice:
    image: knowledge-indexer-service:latest
    build: knowledge-indexer-service/
    restart: always
    network_mode: host
#    depends_on: neo4j!
#      - eurekaserver
#      - rabbitmq
    ports:
      - 8000:8000
    expose:
      - 8000

  Angular-frontend:
    build: Angular-frontend/
    image: plasma-front-end
    container_name: plasma-front-end
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200
    restart: always





 taggingservice:
  image: tagging-service:latest
  build: tagging-service/
  restart: always
  network_mode: host
  depends_on:
    - eurekaserver
  ports:
    - 8070:8070
  expose:
    - 8070